import numpy as np
import control
from tqdm import tqdm
from concurrent.futures import ProcessPoolExecutor, as_completed
import multiprocessing
import warnings
warnings.filterwarnings("ignore")
import time

FINAL_T = 15
N_POINTS = 5000
TAU = 5e-2
DEVIATION = np.pi / 12

# Pre-generate noise/disturbance once (same as notebook)
def _build_signals():
    np.random.seed(42) # because it has been generated by AI
    time = np.linspace(0, FINAL_T, N_POINTS)
    lowpass  = control.zpk([], [-1/TAU]*3, (-1/TAU)**3, dt=0)
    highpass = 1 - lowpass
    white_noise = control.white_noise(time, np.array([[1e-4, 0], [0, 0.1]]))
    disturbance = control.forced_response(lowpass,  T=time, U=white_noise[1])
    noise       = control.forced_response(highpass, T=time, U=white_noise[0])
    return time, disturbance.y, noise.y

# cartpole as notebook
def _build_system():
    def cartpole_update(t, x, u, params):
        g, mc, mp, l = 9.81, 1.0, 0.1, 0.5
        _, x_dot, theta, theta_dot = x
        F = u[0] + u[1]
        sin_theta = np.sin(theta)
        cos_theta = np.cos(theta)
        divisor   = mc + mp * sin_theta**2
        x_ddot     = (F + mp*sin_theta*(l*theta_dot**2 + g*cos_theta)) / divisor
        theta_ddot = (-F*cos_theta - mp*l*theta**2*sin_theta*cos_theta
                      - (mc+mp)*g*sin_theta) / (l * divisor)
        return [x_dot, x_ddot, theta_dot, theta_ddot]

    def cartpole_output(t, x, u, params):
        return x[2] + u[-1]

    return control.nlsys(
        cartpole_update, cartpole_output,
        inputs=('u', 'v', 'w'), outputs=(r'$\theta$'),
        states=('x', 'x_dot', r'$\theta$', 'theta_dot'),
        name='cartpole'
    )

# closed loop method (reused)
def simulate(kp, ki, kd, time, disturbance_y, noise_y,
             use_noise=False, use_disturbance=False):
    """Returns scalar cost (lower = better). Returns np.inf on failure."""
    try:
        SYSTEM = _build_system()
        pid = (control.tf([kp], [1])
               + control.tf([ki], [1, 0])
               + control.tf([kd, 0], [1e-3, 1]))
        pid.update_names(name='pi_controller')

        open_loop = control.interconnect(
            [SYSTEM, pid],
            connections=[['cartpole.u', 'pi_controller.y']],
            inplist=['pi_controller.u', 'cartpole.v', 'cartpole.w'],
            outlist=[r'cartpole.$\theta$'],
            name='open_loop'
        )
        sum_junc = control.summing_junction(2, 1, name='sum_junc')
        closed_loop = control.interconnect(
            [open_loop, sum_junc],
            connections=[['sum_junc.u[1]', '-open_loop.y[0]'],
                         ['open_loop.u[0]', 'sum_junc.y[0]']],
            inplist=['sum_junc.u[0]', 'open_loop.u[1]', 'open_loop.u[2]'],
            outlist=['open_loop.y[0]'],
            name='closed_loop'
        )

        inputs = np.zeros((3, len(time)))
        inputs[0] += np.pi
        if use_noise:
            inputs[2] = 1.0 * noise_y
        if use_disturbance:
            inputs[1] = 1.0 * disturbance_y

        result = control.input_output_response(
            closed_loop, U=inputs,
            X0=[0, 0, np.pi - DEVIATION, 0],
            T=time, squeeze=True
        )

        theta = result.states[2]

        # cost function
        # Penalise: divergence, overshoot, steady-state error, settling time
        if np.any(np.isnan(theta)) or np.any(np.abs(theta) > 100):
            return np.inf

        error       = theta - np.pi
        ise         = np.trapz(error**2, time)                  # integral squared error
        overshoot   = max(0, np.max(np.abs(error)) - abs(error[0]))  # extra beyond initial
        final_error = np.mean(np.abs(error[-200:]))             # last ~0.6 s

        cost = ise + 5.0 * overshoot + 20.0 * final_error
        return float(cost)

    except Exception:
        return np.inf

def _worker(args):
    """Evaluate a single (kp, ki, kd) triple. Args packed for pickling."""
    kp, ki, kd, time, dist_y, noise_y, use_noise, use_dist = args
    cost = simulate(kp, ki, kd, time, dist_y, noise_y, use_noise, use_dist)
    return cost, kp, ki, kd


# sometime random is more efficient than order
def random_search(question, n_samples, use_noise, use_disturbance,
                  kd_fixed_zero=False, n_workers=None):
    if n_workers is None:
        n_workers = max(1, multiprocessing.cpu_count() - 1)

    time, dist_y, noise_y = _build_signals()

    rng = np.random.default_rng(0)
    kp_vals = rng.uniform(0, 100, n_samples)
    ki_vals = rng.uniform(0, 100, n_samples)
    kd_vals = np.zeros(n_samples) if kd_fixed_zero else rng.uniform(0, 100, n_samples)

    args_list = [
        (kp_vals[i], ki_vals[i], kd_vals[i],
         time, dist_y, noise_y, use_noise, use_disturbance)
        for i in range(n_samples)
    ]

    best_cost = np.inf
    best_params = (1.0, 0.0, 0.0)

    with ProcessPoolExecutor(max_workers=n_workers) as executor:
        futures = {executor.submit(_worker, a): i for i, a in enumerate(args_list)}
        with tqdm(total=n_samples, desc="Searching", unit="eval",
                  dynamic_ncols=True, colour="cyan") as pbar:
            for future in as_completed(futures):
                cost, kp, ki, kd = future.result()
                if cost < best_cost:
                    best_cost = cost
                    best_params = (kp, ki, kd)
                    pbar.set_postfix(
                        cost=f"{best_cost:.4f}",
                        kp=f"{kp:.2f}", ki=f"{ki:.2f}", kd=f"{kd:.2f}"
                    )
                pbar.update(1)

    #Local refinement using scipy
    print("  Refining best solution locally ", end=" ", flush=True)
    from scipy.optimize import minimize

    def obj(params):
        kp, ki = params[:2]
        kd = 0.0 if kd_fixed_zero else params[2]
        if kp < 0 or ki < 0 or kd < 0 or kp > 100 or ki > 100 or kd > 100:
            return 1e9
        return simulate(kp, ki, kd, time, dist_y, noise_y, use_noise, use_disturbance)

    x0 = list(best_params[:2]) if kd_fixed_zero else list(best_params)
    res = minimize(obj, x0, method='Nelder-Mead',
                   options={'xatol': 0.01, 'fatol': 0.01, 'maxiter': 500, 'disp': False})
    print("done")

    if res.fun < best_cost:
        best_cost = res.fun
        if kd_fixed_zero:
            best_params = (max(0, res.x[0]), max(0, res.x[1]), 0.0)
        else:
            best_params = tuple(max(0, v) for v in res.x[:3])

    kp, ki, kd = best_params
    print(f"\nBest cost : {best_cost:.6f}")
    if kd_fixed_zero:
        print(f"     kp = {kp:.4f},  ki = {ki:.4f}  (kd fixed = 0)")
    else:
        print(f"     kp = {kp:.4f},  ki = {ki:.4f},  kd = {kd:.4f}")

    return best_params, best_cost


if __name__ == "__main__":
    # Number of random samples per question
    # heat number as high it is , 
    # at high heat will output from your machine
    N = 6000

    results = {}

    params, cost = random_search(
        "Q4-PI Controller  (kp + ki only, kd=0)",
        n_samples=N,
        use_noise=False, use_disturbance=False,
        kd_fixed_zero=True
    )
    results["Q4"] = params

    params, cost = random_search(
        "Q5-PID Controller  (no noise, no disturbance)",
        n_samples=N,
        use_noise=False, use_disturbance=False,
        kd_fixed_zero=False
    )
    results["Q5"] = params


    print("\n" + "="*55)
    print("  FINAL RESULTS SUMMARY")
    print("="*55)
    kp, ki, kd = results["Q4"]
    print(f"  Q4 (PI)   kp={kp:.3f},  ki={ki:.3f}")
    kp, ki, kd = results["Q5"]
    print(f"  Q5 (PID)  kp={kp:.3f},  ki={ki:.3f},  kd={kd:.3f}")
    print("="*55)
