#import "@preview/subpar:0.2.2"
#import "lib.typ": project 
#import "@preview/dashy-todo:0.1.3": todo
#import "@preview/wrap-it:0.1.1": *
#set text(font: "xits")
#set cite(style: "ieee")
#show: project.with(
  title: "Laboratory 1",
  subtitle: "SYST0022-1 Linear systems design",
  authors: (
    "Loïc DELBARRE",
    "S215072"
  ),
  school-logo: image("ulgfsa.svg"),
  branch: "Engineering physics",
  academic-year: "2025-2026",
  tof: false,
  tot: false,
  toc: false,
  footer-text: "Laboratory 1"
)

#set par(justify: true)
#set page(paper: "a4")
#set text(size: 12pt)
#set page(numbering: "1")
#set math.equation(numbering: "(1)", number-align: bottom)
#import "@preview/zero:0.5.0": ztable
#import "@preview/theorion:0.4.1": *
#import cosmos.clouds: *
#show: show-theorion
#let theorem = theorem.with(fill: blue.lighten(85%))
#let theorem-box = theorem-box.with(fill: blue.lighten(85%))
#let theorem-box = theorem-box.with(radius: 5pt)
#import "@preview/physica:0.9.7": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge

= Question 1
/*
* - frequency domain 
* - Diagram errors
* - too many errors
*/
#quote-box[
#set text(fill: black)
Let $P(s)$ denote the plant transfer function. Draw the block diagram of a closed-loop system controlled with a PID controller.
The controller block should be detailed into its proportional, integral, and derivative actions in frequency domain form.
]
The block diagram of a closed-loop system controlled with a PID controller can be seen as :
#diagram(
  node-stroke: 0.8pt,
  edge-stroke: 0.8pt,
  node-corner-radius: 2pt,
  spacing: (14mm, 10mm),
  node(
    enclose: (<sum>, <pid>, <plant>, <tap>, <neg>, <fb1>, <fb2>),
    stroke: (paint: gray, dash: "dashed", thickness: 0.8pt),
    fill: none,
    corner-radius: 4pt,
    snap: false,
    label: align(bottom + right)[#text(rgb("#444444"))[$G_("ry")(s)$]],
    name: <box>
  ),
  node((0,0), $r(s)$, stroke: none, name: <r>),
  node((1,0), $+$, shape: circle, width: 7mm, name: <sum>),
  node((2.5,0),
    align(center)[
      $C(s)$ \
      #v(5pt)
      $= k_P + display(k_I/s) + display(k_D s)$
    ],
    width: 38mm, height: 20mm,
    name: <pid>
  ),
  node((4.5,0),
    $P(s)$,
    width: 18mm, height: 10mm,
    name: <plant>
  ),
  node((5.5, 0), stroke: none, name: <tap>),
  node((6.5, 0), $y(s)$, stroke: none, name: <y>),
  node((5.5, 1.1), stroke: none, name: <fb1>),
  node((1,   1.1), stroke: none, name: <fb2>),
  node((3.5, 1.1),
    $-1$,
    width: 12mm, height: 10mm,
    name: <neg>
  ),
  edge(<r>, <sum>, "-|>"),
  edge(<sum>, <pid>, "-|>", label: $e(s)$, label-pos: 0.3),
  edge(<pid>, <plant>, "-|>", label: $u(s)$, label-pos: 0.45),
  edge(<plant>, <tap>, "-"),
  edge(<tap>, <y>, "-|>"),
  edge(<tap>, <fb1>, "-"),
  edge(<fb1>, <neg>, "-|>"),
  edge(<neg>, <fb2>, "-"),
  edge(<fb2>, <sum>, "-|>"),
)

Where 

- $r(s)$: Reference (desired output).
- $e(s)$: Error signal, defined as $e(s) = r(s) - y(s)$, representing the difference between reference and actual output.
- $U(s)$: Input control signal generated by the controller to drive the system toward the reference.
- $P(s)$: Plant (system to be controlled), characterized by its transfer function $P(s) = y(s)/u(s)$.
- $C(s)$: Controller, with transfer function $C(s)$ that processes the error signal to produce $u(s)$.
- $y(s)$: System output, influenced by both the control input ,disturbances and noises.
- $G_(y r)(s)$: Closed-loop transfer function, relating the system output $y(s)$ to the reference input $r(s)$.
#pagebreak()
= Question 2
/*
* - No formula details C(s) not developed
* - incorect expression
*/
#quote-box[
#set text(fill: black)
Let $r$ and $y$ denote the reference and the output of the controlled system. Based on the block diagram you drew at the previous point, give the expression of the closed-loop transfer function $G_(y r)(s)$.
] 


#theorem-box(title:
"From the block diagram described in Question 1, the signals are related as"
)[
$ cases(
  e(s)= r(s)-y(s),
  u(s)= e(s) C(s),
  y(s)= P(s) u(s)
) $ 
]
By substituing the definition to the plant output,
$
y(s)= P(s)e(s)C(s)=P(s)C(s)[r(s)-y(s)]
$
$
y(s)[1+P(s)C(s)]= P(s)C(s)r(s)
$
The closed loop transfer function is defined as 
$
G_(y r )= Y(s)/R(s)= (P(s)C(s))/(1+P(s)C(s))= frac(P(s)[k_P +k_d s + k_I s^(-1)],1+P(s)[k_P +k_d s + k_I s^(-1)])
$

= Question 3
/*
* 3 parameter well explained
* 1 parameters is not well explained or lacks of precision
* More thatn 1 parameter is not explained correctly or overall lack of details
*/
#quote-box[
#set text(fill: black)
Intuitively, what would be the effect of modifying each parameter ($k_P$, $k_I$, and $k_D$) independently?
]
=== Proportional Gain $k_P$ (Present)
Directly scales the error signal $e(s)$, providing immediate corrective action.
It counteracts the instantaneous value of the error.
=== Integral Gain $k_I$ (Past)
Accumulates past errors to eliminate steady-state (or static) error.
=== Derivative Gain $k_D$ (Future)
Anticipates future error trends by differentiating $e(s)$, damping oscillations.

= Question 4
/*
* - no good set was found + justification 
* - integral action small justification
*/
#quote-box[
#set text(fill: black)
In the following simulation, tune the proportional and integral gains $k_P$ and $k_I$.

a)  Give a set of values for which the actual angle converges towards the reference angle. In the case you can't find any, what's the apparent problem with the PI controller?
]
/*The PI controller cannot converge correctly, as $k_P$ and $k_I$ increases, the reaction time decrease  but create oscilations.It requires a parameter to anticipate how fast is the convergence torwards r and how fast the error decreases: a derivative gain $k_P$.
*/
The PI controller cannot achieve monotonic convergence. Increasing 
$k_P$  and $k_I$ speeds up the response, but the continuously‑integrated error keeps growing, producing persistent oscillations and overshoot that destabilise the system. In other words, without a derivative term to anticipate the error‑rate, the controller cannot settle on the reference angle.
The inclusion of a derivative term, 
 $k_D$, furnishes the necessary predictive action to attenuate the acceleration of the error. By opposing rapid variations of the error, the derivative contribution mitigates overshoot and curtails oscillatory behavior, thereby enabling the closed‑loop system to settle swiftly while maintaining proximity to the reference signal.

A refined set of tuning parameters that satisfies these requirements is approximately

$k_P≈34.5$ and
$k_I≈ 2 times 10^(-4)$
 (value selected to match the observed damping).
With this combination, the system exhibits rapid convergence and only bounded, well‑controlled oscillations around the desired angle, confirming that the addition of derivative feedback restores both stability and speed, whereas integral action alone degrades overall performance.

#figure(
  image("q4.svg",width:100%),
  caption:[refined solution with $k_P$=34.5361 and $k_I$=0.0002],
)
#quote-box[
#set text(fill: black)
 b) Does the integral action improve the behavior of the control system? Why?
 ]
The integral term can be useful because it eliminates any steady‑state offset that a pure proportional controller would leave behind. By continuously accumulating the tracking error, it drives the controller output toward a value that removes the residual error, thereby improving long‑term accuracy. However, in this cart‑pole system the accumulated error grows too aggressively, forcing the controller to over‑compensate and produce large control actions that push the pole past the upright position. Consequently, while the integral action can reduce steady‑state error, it also accelerates the response in a way that generates overshoot and ultimately destabilises the closed‑loop system. Hence, simply adding integral gain does not lead to a better overall performance unless it is carefully balanced with other controller components

= Question 5
/*
* Nothing correct or lack of explanation
* - parameters set and justification
* - derivative action explanation
*/
#quote-box[
#set text(fill: black)
We will now add a derivative action to the system. Tune the parameters of the PID controller. Give a good set of parameters ($k_P$, $k_I$, and $k_D$) for which the actual distance converges quickly towards the reference angle.
 Explain why the derivative action improves the behavior of the controlled system.
 ]

#figure(
  image("q5.svg",width:100%),
  caption:[ refined solution with $k_P$=99.9997 , $k_I$=68.8360 and $k_D$= 99.9914
  ],
)<q5>
The @q5 illustrates that, with the PID gains $k_P=99.9997$ , $k_I=68.8360$ and $k_D= 99.9914$, the closed‑loop response of the cart‑pole system exhibits negligible oscillatory behavior and rapidly settles onto the prescribed reference trajectory. The large proportional gain provides a strong corrective effort, while the integral term eliminates the steady‑state deviation, and the pronounced derivative gain introduces significant phase lead, thereby increasing system damping and suppressing overshoot. Consequently, the actual angular position $theta(t)$ tracks the reference angle $theta_(r e f)(t)$ with high fidelity, confirming that the derivative action critically improves transient performance by shaping the loop’s frequency response and enhancing stability margins.
#pagebreak()
= Question 6
/*
* - Incorect or lacks of explanation 
* Load/Sensor noise explanation
* - validity of explanation
*/
#quote-box[
#set text(fill: black)
We will keep the same set of parameters you found at the previous point and add some disturbance on the control (the force $f_x$ applied) and measurement noise on the output of the angle sensor.
 Is your design still valid when noise is added? Explain why focusing on your controller components.
]
== Disturbance
#figure(
  image("q6_dist.svg",width:100%),
  caption:[ distortion enabled
  ],
)<disturb>
When a load disturbance acts on the input channel (@disturb), the proportional term ($k_D$) delivers a strong corrective effort that counteracts the added torque, limiting the amplitude of the resulting oscillations. The integral action ($k_I$) eliminates any steady‑state offset left by the disturbance, while the derivative action continues to add damping, ensuring that the system returns to the reference trajectory without excessive overshoot.

== Noise
#figure(
  image("q6_noise.svg",width:100%),
  caption:[ measurement noise enabled
  ])<noisy>
In the noise‑only (@noisy) scenario the controller first produces a modest oscillation because the proportional term ($k_P$) reacts to the low‑amplitude measurement perturbation with a limited corrective effort; the derivative action ($k_D$) initially suppresses the high‑frequency component, so the response remains small. As the noisy signal accumulates, the derivative term continues to generate a growing control effort that the integral action ($k_I$) integrates, gradually increasing the effective gain seen by the system. Once the integrated error reaches a threshold, the closed‑loop torque command amplifies the original disturbance, leading to the observed transition from a small‑amplitude oscillation to a large, sustained one. 

