#import "@preview/subpar:0.2.2"
#import "lib.typ": project 
#import "@preview/dashy-todo:0.1.3": todo
#import "@preview/wrap-it:0.1.1": *
#set text(font: "xits")
#set cite(style: "ieee")
#show: project.with(
  title: "Laboratory 2",
  subtitle: "SYST0022-1 Linear systems design",
  authors: (
    "Loïc DELBARRE",
    "S215072"
  ),
  school-logo: image("ulgfsa.svg"),
  branch: "Engineering physics",
  academic-year: "2025-2026",
  tof: false,
  tot: false,
  toc: false,
  footer-text: "Laboratory 2"
)

#set par(justify: true)
#set page(paper: "a4")
#set text(size: 12pt)
#set page(numbering: "1")
#set math.equation(numbering: "(1)", number-align: bottom)
#import "@preview/zero:0.5.0": ztable
#import "@preview/theorion:0.4.1": *
#import cosmos.clouds: *
#show: show-theorion
#let theorem = theorem.with(fill: blue.lighten(85%))
#let theorem-box = theorem-box.with(fill: blue.lighten(85%))
#let theorem-box = theorem-box.with(radius: 5pt)
#import "@preview/physica:0.9.7": *
#import "@preview/fletcher:0.5.8" as fletcher: diagram, node, edge

= Question 1
/*
* - frequency domain 
* - Diagram errors
* - too many errors
*/
#quote-box[
#set text(fill: black)
Let $P(s)$ and $C(s)$ denote the plant and controller transfer functions respectively. 
 
 a) Draw the block diagram of the closed-loop system. Your diagram should include the following signals:
  -   the reference $r(t)$,
  -   the controlled input $u(t)$,
  -   the controlled output $y(t)$,
  -   the load disturbance $d(t)$,
  -   the output noise $n(t)$.
]
The standard feedback block diagram is shown in @fig-blockdiagram. The controller
$C(s)$ processes the tracking error $e(t) = r(t) - y(t)$ to generate the
control input $u(t)$. The load disturbance $d(t)$ enters at the plant input,
while the measurement noise $n(t)$ corrupts the output before it reaches the
feedback path.
#figure(
diagram(
  node-stroke: 0.8pt,
  edge-stroke: 0.8pt,
  node-corner-radius: 2pt,
  spacing: (14mm, 10mm),
  node((0,0), $r(t)$, stroke: none, name: <r>),
  node((3.6,-0.8), $d(t)$, stroke: none, name: <dist>),
  node((5.3,-0.8), $n(t)$, stroke: none, name: <noice>),
  node((1,0), $+$, shape: circle, width: 7mm, name: <sum>),
  node((2.3,0),
    align(center)[
      $C(s)$ \
      $= k_P + k_I frac(d e(t),d t) + integral_0^t e(tau) d tau$
    ],
    width: 38mm, height: 20mm,
    name: <pid>
  ),
  node((3.6,0), $+$, shape: circle, width: 7mm, name: <sumd>),
  node((4.5,0),
    $P(s)$,
    width: 18mm, height: 10mm,
    name: <plant>
  ),
  node((5.7, 0), stroke: none, name: <tap>),
  node((6.5, 0), $y(t)$, stroke: none, name: <y>),
  node((5.7, 1.1), stroke: none, name: <fb1>),
  node((5.3,0.), $+$, shape: circle, width: 7mm, name: <sumk>),
  node((1,   1.1), stroke: none, name: <fb2>),
  node((3.5, 1.1),
    $-1$,
    width: 12mm, height: 10mm,
    name: <neg>
  ),
  edge(<r>, <sum>, "-|>"),
  edge(<sum>, <pid>, "-|>", label: $e(t)$, label-pos: 0.3),
  edge(<pid>, <sumd>, "-|>", label: $u(t)$, label-pos: 0.45),
  edge(<dist>, <sumd>, "-|>"),
  edge(<sumd>, <plant>, "-|>"),
  edge(<plant>,<sumk>,"-|>"),
  edge(<sumk>,<tap>,"-"),
  edge(<tap>, <y>, "-|>"),
  edge(<noice>, <sumk>, "-|>"),

  edge(<tap>, <fb1>, "-"),
  edge(<fb1>, <neg>, "-|>"),
  edge(<neg>, <fb2>, "-"),
  edge(<fb2>, <sum>, "-|>"),
)) <fig-blockdiagram>

Where 

- $r(t)$: Reference (desired output).
- $e(t)$: Error signal, defined as $e(s) = r(s) - y(s)$, representing the difference between reference and actual output.
- $u(t)$: Input control signal generated by the controller to drive the system toward the reference.
- $p(t)$: Plant (system to be controlled), characterized by its transfer function $P(s) = y(s)/u(s)$.
- $c(t)$: Controller, with transfer function $C(s)$ that processes the error signal to produce $u(s)$.
- $y(t)$: System output, influenced by both the control input ,disturbances and noises.
- $d(t)$: load disturbance acting at the plant input;
- $n(t)$: measurement noise acting at the plant output;
#quote-box[
#set text(fill: black)
b) Give the expression of $Y(s)$, the Laplace transform of the output signal, as a function of $R(s)$, $D(s)$ and $N(s)$, the Laplace transforms of $r(t)$, $d(t)$ and $n(t)$ respectively.
]

#theorem-box(title:
"From the block diagram described in Question 1, the signals are related as"
)[
$ cases(
  E(s)= R(s)-Y(s),
  U(s)= E(s) C(s),
  Y(s)= N(s) + P(s) [ U(s) + D(s)]
) $ 
]
Substituting $U(s) = C(s)[R(s) - Y(s)]$ into the third equation and collecting
terms in $Y(s)$:
$ Y(s) &= P(s)[C(s) (R(s) - Y(s))+ D(s)]+ N(s) \
  &= P(s)C(s)R(s)- P(s)C(s)Y(s)+P(s)D(s)+N(s)
$
Isolating, and dividing by $1 + P(s)C(s)$ yields the output decomposition:
$ Y(s) [ 1+ P(s)C(s) ] = P(s) C(s) R(s) + P(s) D(s) + N(s) $
$ Y(s)  = frac( P(s) C(s), 1+ P(s)C(s) ) R(s) + frac( P(s) , 1+ P(s)C(s) ) D(s) +frac( 1 , 1+ P(s)C(s) ) N(s) $
= Question 2
#quote-box[
#set text(fill: black)
What do we call the *gang of 4* in control theory? Can you give the general expression and briefly explain what describe the complementary sensitivity function, the load disturbance sensitivity function, and the sensitivity function?
(You may refer to the block diagram of the closed-loop system you drew in Q1.)
]
The *Gang of Four* refers to the four transfer functions that completely
characterise a single-loop feedback system. They are obtained by expressing
both the output $Y(s)$ and the control input $U(s)$ in terms of $R(s)$,
$D(s)$, and $N(s)$.

From Q1, $Y(s)$ is already known. Isolating $U(s)$ in the same way:
$ U(s)&= C(s)[R(s)-Y(s)] \ 
      &= C(s)[R(s)- N(s)-P(s)U(s)-P(s)D(s)] \
      &= C(s)R(s)-C(s) N(s)-P(s)C(s)U(s)-P(s)C(s)D(s)] \
$ 
$
U(s)[1+P(s)C(s)]= C(s)R(s)-C(s)N(s) - P(s)C(s)D(s)
$
#let hb(x, color: blue) = box(baseline: 40%, fill: color.lighten(70%), inset: 8pt, radius: 2pt)[$#x$]
$
U(s)=  hb(frac(C(s), 1+P(s)C(s)),color: #purple)R(s)  - hb(frac(P(s)C(s), 1+P(s)C(s)),color: #green)D(s)- hb(frac(C(s), 1+P(s)C(s)),color: #purple) N(s)
$
$ Y(s)  = hb(frac( P(s) C(s), 1+ P(s)C(s) ),color: #green) R(s) + hb(frac( P(s) , 1+ P(s)C(s) )) D(s) +hb(frac( 1 , 1+ P(s)C(s) ),color: #orange) N(s) $

- Complementary sensitivity function 
$T(s)=hb(frac(P(s)C(s), 1+P(s)C(s)),color: #green)$
- Noise sensitivity function 
$C S(s)=hb(frac(C(s), 1+P(s)C(s)),color: #purple)$
- sensitivity function 
$S(s)= hb(frac( 1 , 1+ P(s)C(s) ),color: #orange) $
- Load sensitivity function
$P S (s) = hb(frac( P(s) , 1+ P(s)C(s) )) $
= Question 3
#quote-box[
#set text(fill: black)
Compute the poles and zeros of the plant transfer function $P(s)$. 
 Can you assess the stability of the system by using only the simplified Nyquist criterion? Why?
]
The linearised plant transfer function is:
    $ P(s) = frac(1,l dot m_c dot s^2 - g dot (m_c + m_p)) $  

*Zeros:* The numerator is constant; $P(s)$ has no finite zeros.

*Poles:* Setting the denominator to zero:
$ l dot m_c dot s^2 - g dot (m_c + m_p) = 0$ 
$ s = plus.minus sqrt(frac(g(m_c+m_p),l dot m_c)) $
where $l = 0.5$ m, $m_c = 1$ kg, $m_p = 0.1$ kg, and $g = 9.81$ m/$s^2$.

#let g = 9.81
#let mc = 1.0
#let mp = 0.1
#let l = 0.5
#let s_val = calc.sqrt(g * (mc + mp) / (l * mc))
// too lazy to compute , just ask nicely typst
$ s approx plus.minus #calc.round(s_val, digits: 4) $

The simplified (gain-based) Nyquist criterion applies only to *open-loop stable*
plants. Since $P(s)$ has a pole at $s = +#calc.round(s_val, digits: 4)$ rad/s
in the open right half-plane, the simplified criterion *cannot* be used; the
full Nyquist criterion must be applied instead.
= Question 4
#quote-box[
#set text(fill: black)
Without any control, is the system stable ? Justify your answer.
Below are the Bode and Nyquist plots of $P(s)$. It also shows how the output evolves in open-loop when the system experiences disturbance $d(t)$.
]
The uncontrolled plant is *unstable*. The right half-plane pole at
$s = +#calc.round(s_val, digits: 4)$ rad/s means that any infinitesimal
perturbation causes the state to diverge exponentially. @fig-openloop confirms
this across all four panels: the Bode magnitude grows unboundedly at low
frequencies with no 0 dB crossover from above; 
the Nyquist curve lies entirely on the negative real axis between $-0.0927$
and $0$; since $P(s)$ has an open-loop RHP pole, the full Nyquist criterion
must be applied and no conclusion can be drawn from encirclement of $-1+0j$
alone;
finally, the
time response to $d(t) = sin(4 pi t)$ shows the pole angle $theta(t)$
diverging exponentially, consistent with the poles at
$s approx plus.minus #calc.round(s_val, digits: 3)$ rad/s.
#figure(
  image("q4.svg", width: 100%),
  caption: [
    Open-loop analysis of the uncontrolled cart-pole.
  ]
) <fig-openloop>
#let tau  = 0.02          // delay tolerance [s]
#let omega_star = 4 * calc.pi   // disturbance frequency [rad/s]
#let omega_c    = 2 * omega_star // crossover frequency [rad/s]

= Question 5
#quote-box[
#set text(fill: black)
Choose the phase margin $phi.alt()_m$ such that a delay of $tau = 20$ ms is acceptable.
]
The disturbance frequency is $omega^star = 4pi approx #calc.round(omega_star, digits: 3)$ rad/s.
The gain crossover frequency is chosen as:
$
omega_c = 2 omega^star approx #calc.round(omega_c, digits: 3) "rad/s."
$


// ── Q5 ───────────────────────────────────────────────────────
#let phi_m_rad = tau * omega_c
#let phi_m_deg = phi_m_rad * 180 / calc.pi
A pure time delay $tau$ introduces a phase lag of $tau omega$ at each
frequency $omega$. At the gain crossover, this lag equals
$tau omega_c$. For the closed loop to remain stable in the presence of this
delay, the phase margin must satisfy:

$
phi_m >= tau\,omega_c
= #tau times #calc.round(omega_c, digits: 4)
approx #calc.round(phi_m_rad, digits: 4) "rad"
= #calc.round(phi_m_deg, digits: 2) degree.
$

#block(
  fill: luma(240),
  inset: 8pt,
  radius: 4pt,
)[
The phase margin is selected as $phi_m = #calc.round(phi_m_deg, digits: 1) degree$, which ensures
stability for any delay up to $tau = 20$ ms.
]
= Question 6
#quote-box[
#set text(fill: black)
We want the maximal increase in phase induced by the lead compensator to occur at the gain crossover frequency. From $phi.alt()_m$, compute the value of $m$, under the assumption that there is no PI block and $angle P(j omega_c) = -pi$. Multiply the value you found by 2 so that an additional delay margin is added, with a small cost on performance. 
(As a reminder, the variable $m$ defines the space between the pole and zero of the lead compensator, i.e., $|p|=m|z|$.)
]

// ── Q6 ───────────────────────────────────────────────────────
#let sin_phi = calc.sin(phi_m_rad)
#let m_raw   = (1 + sin_phi) / (1 - sin_phi)
#let m       = 2 * m_raw     // × 2 safety factor

A lead compensator $K(s+z)/(s+p)$ with $p = m z$ provides a maximum phase
advance of:
$
phi_"max" = arcsin frac(m-1,m+1).
$

Since $angle P(j omega_c) = -pi$, the plant contributes $-180degree$ at
crossover and the compensator must supply the full phase margin $phi_m$.
Setting $phi_"max" = phi_m = #calc.round(phi_m_deg, digits: 2) $ and solving for $m$:

$ m = (1 + sin phi_m)/(1 - sin phi_m)
    = (1 + #calc.round(sin_phi, digits: 4)) /
      (1 - #calc.round(sin_phi, digits: 4))
    approx #calc.round(m_raw, digits: 4) $

Doubling to provide an additional delay margin with marginal performance cost:
#block(
  fill: luma(240),
  inset: 8pt,
  radius: 4pt,
)[
  $ m = 2 times #calc.round(m_raw, digits: 4)
      approx #calc.round(m, digits: 4) $
]
= Question 7

#quote-box[
#set text(fill: black)
Find the zero and pole locations so that the increase in phase margin induced by the lead compensator occurs at the gain crossover frequency.
]

// ── Q7 ───────────────────────────────────────────────────────
#let z = omega_c / calc.sqrt(m)
#let p = m * z


The maximum phase advance of $K(s+z)/(s+p)$ occurs at the geometric mean
of the zero and pole:
$
omega_"max" = sqrt(z abs(p)) = z sqrt(m).
$
$ z = omega_c / sqrt(m)
    = #calc.round(omega_c, digits: 4) / sqrt(#str(calc.round(m, digits: 4)))
    approx #calc.round(z, digits: 4) "rad/s" $
$ abs(p) = m  z
    = #calc.round(m, digits: 4) times #calc.round(z, digits: 4)
    approx #calc.round(p, digits: 4) "rad/s" $

#block(
  fill: luma(240),
  inset: 8pt,
  radius: 4pt,
)[
  Zero at $z approx #calc.round(z, digits: 2)$ rad/s,
  pole at $p approx #calc.round(p, digits: 2)$ rad/s.
]
= Question 8
#quote-box[
#set text(fill: black)
Knowing that $|P(j omega_c)| = -50.2808$ dB, give the value of $K$ such that $omega_c$ stays the gain crossover frequency.
]
#let P_dB  = -50.2808
#let P_lin = calc.pow(10, P_dB / 20)
#let lead_mag = calc.sqrt(omega_c * omega_c + z * z) / calc.sqrt(omega_c * omega_c + p * p)
#let K = 1 / (lead_mag * P_lin)

#let z_lead = omega_c / calc.sqrt(m)
#let p_lead = m * z_lead

At the gain crossover, the loop gain must satisfy $|C(j omega_c) P(j omega_c)| = 1$.
The magnitude of the lead compensator (without $K$) at $omega_c$ is:
$ |"Lead"(j omega_c)| = sqrt(omega_c^2 + z^2)/sqrt(omega_c^2 + p^2)
  approx #calc.round(lead_mag, digits: 4) $

Converting $|P(j omega_c)| = #P_dB$ dB to linear scale gives
$|P(j omega_c)| approx #calc.round(P_lin, digits: 6)$. The gain $K$ is then:

Therefore:
$ K = 1/(|"Lead"| times |P|)
    = 1/(#calc.round(lead_mag, digits: 4) times #calc.round(P_lin, digits: 6))
    approx #calc.round(K, digits: 4) $

#block(
  fill: luma(240),
  inset: 8pt,
  radius: 4pt,
)[
  $K approx #calc.round(K, digits: 1)$
  (#calc.round(20 * calc.log(K, base: 10), digits: 2) dB)
]

@fig-lead verifies the lead-compensator design across all four panels: the Bode
magnitude confirms the gain crossover at $omega_c approx #calc.round(omega_c, digits: 1)$
rad/s as designed; the Bode phase shows a margin of
$phi_m >= #calc.round(phi_m_deg, digits: 1) degree$ at crossover, satisfying the
delay-robustness specification of $tau = 20$ ms; the Nyquist curve makes exactly
one counter-clockwise encirclement of $-1+0j$, which accounting for the single
open-loop RHP pole of $P(s)$ is consistent with a stable closed loop; finally,
the disturbance response confirms stabilisation, with $theta(t)$ returning to
equilibrium once $d(t)$ ceases.

#figure(
  image("q8.svg", width: 100%),
  caption: [
    Lead-compensator design verification
    ($K approx #calc.round(K, digits: 1)$,
    $z approx #calc.round(z_lead, digits: 2)$ rad/s,
    $p approx #calc.round(p_lead, digits: 2)$ rad/s).
    *(Top-left)* Bode magnitude: gain crossover at $omega_c approx #calc.round(omega_c, digits: 1)$ rad/s.
    *(Bottom-left)* Bode phase: margin $phi_m >= #calc.round(phi_m_deg, digits: 1) degree$.
    *(Top-right)* Nyquist diagram: one counter-clockwise encirclement of $-1+0j$, confirming closed-loop stability.
    *(Bottom-right)* Disturbance response: $theta(t)$ returns to equilibrium.
  ]
) <fig-lead>
= Question 9
#quote-box[
#set text(fill: black)
Use the simulation below to find a value for $z_(P I)$ that gives you a good closed-loop system response to the disturbance $d(t)$. Justify the positioning of $z_(P I)$ w.r.t. $omega_c$.
]

The full controller is $C(s) = K(s+z)/(s+p) \cdot (s + z_"PI")/s$.
The integrator pole at the origin guarantees zero steady-state error for
constant inputs or disturbances, while the PI zero $z_"PI"$ prevents excessive
phase lag near crossover.

To preserve the phase margin designed in Q5–Q7, $z_"PI"$ must satisfy
$z_"PI" << omega_c$. A standard rule of thumb is $z_"PI" approx omega_c/10$:


$
z_"PI" approx frac(omega_c, 10) = frac(#str(calc.round(omega_c, digits: 2)), 10) approx #calc.round(omega_c / 10, digits: 2) "rad/s."
$
#figure(
  image("q9.svg", width: 100%),
  caption: [
    Closed-loop disturbance response with the lead + PI controller
    ($z_"PI" approx #calc.round(omega_c / 10, digits: 2)$ rad/s).
    The pole angle $theta(t)$ is driven to zero after the disturbance
    $d(t)$ (a sinusoidal burst at $omega^star = 4pi$ rad/s, active for
    $t in [0, 0.25]$ s). Placing $z_"PI"$ well below $omega_c$ ensures
    the phase margin at crossover is not degraded.
  ]
) <fig-pi>

= Question 10
#quote-box[
#set text(fill: black)
As far as the closed-loop response to disturbance is concerned, it seems that the PI block has added nothing to our design. The two cells below compute respectively the gang of four for the system controlled with a lead compensator and the system controlled with a lead compensator + PI block. Based on the comparison between both cases, comment on the usefulness of the PI block.
]
@fig-gof compares the Gang of Four for both controllers. In the closed-loop
disturbance response, the PI block appears to offer no visible improvement over
the lead compensator alone ,this is expected, since $d(t)$ is a sinusoidal
burst at $omega^star = 4pi approx 12.6$ rad/s, well above $z_"PI"$, so the
integrator is never excited. The Gang of Four reveals where the PI does matter:
$S(s)$ satisfies $|S(j 0)| = 0$, guaranteeing zero steady-state tracking error,
while $|P S(j 0)| = 0$ ensures constant disturbances are rejected entirely
neither property holds for the lead-only controller.

#figure(
  image("q10.svg", width: 100%),
  caption: [
    Gang of Four: lead only (dashed) vs.\ lead + PI (solid).
    *(Top-left) $T(s)$*: similar tracking bandwidth for both controllers.
    *(Top-right) $P S(s)$*: the PI drives $|P S(j 0)|$ to zero, eliminating steady-state disturbance offset.
    *(Bottom-left) $C S(s)$*: the PI adds low-frequency gain, reflecting higher control effort for constant disturbance rejection.
    *(Bottom-right) $S(s)$*: the PI achieves $|S(j 0)| = 0$; the lead-only controller leaves $S(0) > 0$.
  ]
) <fig-gof>
